#ifndef BLACKBOARDCORE_GLOBAL_H
#define BLACKBOARDCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BLACKBOARDCORE_LIBRARY)
#  define BLACKBOARDCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define BLACKBOARDCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BLACKBOARDCORE_GLOBAL_H
